---
default_language_version:
  python: python3

repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: files/(issue|motd)
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: pretty-format-json
        args:
          - --autofix
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['-c=.ci/yamllint']

  - repo: 'https://github.com/psf/black'
    rev: 24.10.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: pylint
        args:
          [
            "--rcfile=.ci/pylintrc",
            "--spelling-dict=en",
            "--output-format=github",
          ]
        name: pylint
        entry: pylint
        language: system
        types:
          - python

  - repo: 'https://github.com/gruntwork-io/pre-commit'
    rev: v0.1.24
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.30.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - push
