---
name: "Deploy[Compose]"
on:
  workflow_dispatch:
    inputs:
      job_environment:
        type: choice
        description: 'Job environment prod or dev'
        required: true
        default: 'dev'
        options:
          - prod
          - dev
      clean_docker_images:
        type: boolean
        description: 'Clean docker Images'
        required: false

  pull_request:
    branches:
      - main
    types:
      - closed


jobs:
  Checkout_repos:
    runs-on:
      - self-hosted
    environment: ${{ inputs.job_environment }}
    steps:
      - name: Clean old Docker images
        run: docker system prune -a -f
        if: "{{ inputs.clean_docker_images == true}}"

      - name: Checkout current repo
        uses: actions/checkout@v3

  Build_docker_image:
    needs: [Checkout_repos]
    runs-on:
     - self-hosted
    steps:

      - name: Build Docker image
        uses: mr-smithers-excellent/docker-build-push@v5.8
        with:
          image: ${{env.image_name}}
          tags: $GITHUB_RUN_NUMBER
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check image by Anchore
        run: |
          grype  ${{ secrets.REPO }}/${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:$GITHUB_RUN_NUMBER

  Render_template:
    needs: [Build_docker_image]
    runs-on:
     - self-hosted
    steps:
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        env:
          TF_VAR_IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          TF_VAR_REPO: ${{ secrets.REPO }}
          TF_VAR_VERSION: $GITHUB_RUN_NUMBER
          TF_VAR_JOB_ENV: '${{ inputs.job_environment }}'
          TF_VAR_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TF_VAR_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          TF_VAR_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          TF_VAR_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          TF_VAR_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
        env:
          TF_VAR_IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          TF_VAR_REPO: ${{ vars.REPO }}
          TF_VAR_VERSION: $GITHUB_RUN_NUMBER
          TF_VAR_JOB_ENV: '${{ inputs.job_environment }}'
          TF_VAR_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TF_VAR_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          TF_VAR_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          TF_VAR_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          TF_VAR_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -var VERSION=$GITHUB_RUN_NUMBER
        continue-on-error: true
        env:
          TF_VAR_IMAGE_NAME: ${{ vars.IMAGE_NAME }}
          TF_VAR_REPO: ${{ vars.REPO }}
          TF_VAR_VERSION: $GITHUB_RUN_NUMBER
          TF_VAR_JOB_ENV: '${{ inputs.job_environment }}'
          TF_VAR_POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TF_VAR_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          TF_VAR_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          TF_VAR_POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          TF_VAR_BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

  Run_compose:
    needs: [Render_template]
    runs-on:
     - self-hosted
    steps:
      - name: Validate docker compose file
        run: 'docker compose -f docker_compose_weather_bot_${{ inputs.job_environment }}.yml config --quiet  && printf "Composer files is OK\n" || printf "Compose faile with ERROR\n"'

      - name: Nomad_run
        id: nomad_run
        run: 'docker compose -f docker_compose_weather_bot_${{ inputs.job_environment }}.yml up -d'
