---
name: "Down[Compose]"
on:
  workflow_dispatch:
    inputs:
      job_environment:
        type: choice
        description: 'Job environment prod or dev'
        required: true
        default: 'dev'
        options:
          - prod
          - dev

      clean_docker_images:
        type: boolean
        description: 'Clean docker Images'
        required: false

  pull_request:
    branches:
      - main
    types:
      - closed


jobs:
  compose_Down:
    runs-on: self-hosted
    environment: ${{ inputs.job_environment }}

    steps:
      - name: Docker compose down
        run: >-
          docker compose -f /opt/weather_bot/docker_compose_weather_bot_${{
          github.event_name == 'workflow_dispatch' && inputs.job_environment || 'prod'
          }}.yml down

      - name: Clean old Docker images
        run: docker system prune -a -f
        if: "${{ inputs.clean_docker_images == true }}"
