---
name: Build_image
on: 
  workflow_dispatch
env:
  path_bot: bot_code
  path_nomad: nomad_code
  image_name: tgbot
  repo: ghcr.io


jobs:
  Phase_1:
    runs-on:
      - self-hosted
    steps:
      - name: Clean old Docker images
        run: docker system prune -a -f

      - name: Checkout current repo
        uses: actions/checkout@v3
        with:
          path: ${{env.path_nomad}}

  Phase_2:
    needs: [Phase_1]
    runs-on:
     - self-hosted
    steps:
      - name: Cleanup Docker elements
        run: docker system prune -a --volumes --force

      - name: Debug
        run: ls -la

      - name: Build Docker image
        uses: mr-smithers-excellent/docker-build-push@v5.8
        with:
          image: ${{env.image_name}}
          tags: $GITHUB_RUN_NUMBER
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Check image by Anchore
        run: |
          grype  ${{ env.repo }}/${{ secrets.DOCKER_USERNAME }}/${{ env.image_name }}:$GITHUB_RUN_NUMBER -f high

  Phase_3:
    needs: [Phase_2]
    runs-on:
     - self-hosted
    steps:
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        
      - name: Terraform Init
        id: init
        run: terraform init
        env:
          https_proxy: '164.92.180.74:3128'
          http_proxy: '164.92.180.74:3128'
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        env:
          TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TF_VAR_IMAGE_NAME: ${{env.image_name}}
          TF_VAR_REPO: ${{env.repo}}
          TF_VAR_VER: $GITHUB_RUN_NUMBER

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
        env:
          TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TF_VAR_IMAGE_NAME: ${{env.image_name}}
          TF_VAR_REPO: ${{env.repo}}
          TF_VAR_VER: $GITHUB_RUN_NUMBER
          
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -var ver=$GITHUB_RUN_NUMBER
        continue-on-error: true
        env:
          TF_VAR_DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          TF_VAR_DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TF_VAR_IMAGE_NAME: ${{env.image_name}}
          TF_VAR_REPO: ${{env.repo}}

  Phase_4:
    needs: [Phase_3]
    runs-on:
     - self-hosted
    steps:
      - name: Nomad Plan 
        id: nomad_plan
        run: nomad job plan bot.nomad
        
      - name: Nomad run 
        id: nomad_run
        run: nomad job run bot.nomad






