---
name: Pre-commit
run-name: "Code validation [attempt: #${{ github.run_attempt }}]"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '**'
      - '!master'
      - '!main'
      - '!refs/pull/*'
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  pre-commit:
    runs-on: self-hosted
    container:
      image: ghcr.io/lek-x/lint:v4
      options: -u 1000

    env:
      HOME: /tmp
      UV_CACHE_DIR: /tmp/uv-cache

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Set current repo as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/cache@v4
        name: Cache uv and virtual environment
        with:
          path: |
            /tmp/uv-cache
            ./.venv
          key: precommit-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            precommit-${{ runner.os }}-

      - name: Install project dependencies
        run: uv sync

      - name: Run pre-commit hooks
        run: |
          export PATH="$GITHUB_WORKSPACE/.venv/bin:$PATH"
          prek -c .ci/pre-commit-config.yaml run --all-files
